# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    # Display the navigation bar?
    enable: true
    # Choose a built-in navigation blox or create your own 
    blox: "navbar"
    # Align menu links: 'left', 'center', or 'right'
    align: "center"
    # Fix the navigation bar to the top of the page
    fixed_to_top: true
    # Let the user search from the navigation bar?
    show_search: true
    # Let the user choose between light or dark mode?
    show_theme_chooser: true
    logo:
      text: "Yongjie Hu"
      # Logo filename in 'assets/media/' folder
      filename: "icon.png"

# Site footer This work is licensed under {license}
footer:
  copyright:
    notice: '© {year} Yongjie Hu. '
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math: 
    enable: true
  privacy_pack:
    enable: false
